### PR TITLE
Support proxy routes in development mode when having specified pathname.

### PR DESCRIPTION
**Pull request by stalet**
Bugfix: When specifying a pathname for the podlet, calls to the proxy
route does not match the request in development mode.

### CODE REVIEW

**Comment by trygve-lie** [comment]
Thanks a lot for this :+1: 

One question; does this affect the `publicPathname` on the context?

**Comment by stalet** [comment]
`publicPathname` stays the same for both development mode and not development mode.
Its just the proxy call that adds the missing path when calling to the real service.

This means that we can use `utils.pathnameBuilder(context.publicPathname, '/something')` for enpoints both in development and not development mode without modifications.

**Comment by stalet** [comment]
Before this fix I had to do a workaround in the podlet code:

```
    podlet.proxy({ target: `${development ? podlet.pathname() : ''}/something`, name: 'something' });
    app.get(
        '/something',
        ...
    );
```
When fix is implemented - proxies can be declared like this:
```
    app.get(
        podlet.proxy({ target: '/something', name: 'something' });,
        ...
    );
```

**Comment by stalet** [comment]
I see what you mean. Ill start looking into it.

**Comment by trygve-lie** [comment]
Sweet. Just ask if there is anything.

**Comment by stalet** [comment]
This is not an issue anymore.

**Pull request closed without merging**
